apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: organicsr

resources:
  - 00-namespace.yaml
  - 10-storage-local.yaml
  - 15-secret.yaml
  - 20-deployment.yaml
  - 30-ingress.yaml

# Zentral das Image überschreiben, ohne die Deployment-Datei zu editieren:
#   kubectl kustomize k8s/ | kubectl apply -f -
# oder Tag hier pflegen:
images:
  - name: registry.stoegerer-home.at/organicsr
    newTag: "1.0.0"
