from __future__ import annotations

import json
import re
from pathlib import Path

from contextualize_seed_cards import strip_answer_context, strip_question_context


REPO = Path(__file__).resolve().parents[1]
SEED_PATH = REPO / "app" / "seed_data.json"

SOURCE_NOISE_RE = re.compile(
    r"(?i)\b(systematic review|meta-regression|doi:|trademark|trademarks|"
    r"company overview|company information|internal: confidential|global headquarters|"
    r"regional headquarters|corporate hubs|patent applications|workforce|"
    r"microsoft copilot|marktresearchfuture|guardian|kurier\.at|derstandard|"
    r"welt\.de|copyright|email:|web:|lv-evaluierung|tiss)\b"
)
COMPANY_RE = re.compile(
    r"\b[A-ZÄÖÜ][A-Za-zÄÖÜäöüß'.-]+\s+(AG|GmbH|Inc|Ltd|LLC|International)\b"
)
AUTHOR_RE = re.compile(
    r"\b[A-ZÄÖÜ][A-Za-zÄÖÜäöüß'.-]+\s+[A-Z]\.?\s+[A-ZÄÖÜ][A-Za-zÄÖÜäöüß'.-]+\b"
    r"|\b[A-ZÄÖÜ][A-Za-zÄÖÜäöüß'.-]+\s+[A-ZÄÖÜ][A-Za-zÄÖÜäöüß'.-]+,\s+"
    r"[A-ZÄÖÜ][A-Za-zÄÖÜäöüß'.-]+\s+[A-ZÄÖÜ][A-Za-zÄÖÜäöüß'.-]+\b"
)
META_NOISE_RE = re.compile(
    r"(?i)\b(location|headquarters|corporate hub|source:|notes?:|"
    r"formed from three regional leaders|global organization|global polyolefins platform|"
    r"manufacturing sites|innovation centers|patents?)\b"
)
LECTURE_ADMIN_RE = re.compile(
    r"(?i)\b(vor-?\s*(?:&amp;|&|und)\s*nachbereitung|vorlesungseinheiten|"
    r"prüfungsbogen|pruefungsbogen|prüfungsbeginn|pruefungsbeginn|"
    r"prüfungsantritt|pruefungsantritt|angabezettel|antwortzettel|"
    r"abgabe am ende|zugewiesenen sitzplatz|digitale geräte|digitale geraete|"
    r"sammelort|anmeldeformalitäten|anmeldeformalitaeten|"
    r"positive absolvierung|mindestens 50% der punkte|vorlesungsteile)\b"
)
DOMAIN_KEEP_RE = re.compile(
    r"(?i)\b(haber-bosch|ostwald|bleikammer|claus|solvay|downs|bayer|"
    r"hochofen|zement|ammoniak|salpetersäure|salpetersaeure|"
    r"schwefelsäure|schwefelsaeure|chloralkali|elektrolyse|"
    r"hydrotreatment|cracking|polymerisation|polykondensation)\b"
)


def plain(card: dict) -> str:
    q = strip_question_context(str(card.get("q", "")))
    a = strip_answer_context(str(card.get("a", "")))
    a = re.sub(r"<br><br><span class='source'>.*?</span>\s*$", "", a, flags=re.S)
    text = re.sub(r"<[^>]+>", " ", f"{q} {a}")
    return re.sub(r"\s+", " ", text).strip()


def irrelevant(card: dict) -> bool:
    text = plain(card)
    lower = text.lower()
    if DOMAIN_KEEP_RE.search(text) and not (SOURCE_NOISE_RE.search(text) or LECTURE_ADMIN_RE.search(text)):
        return False
    if SOURCE_NOISE_RE.search(text):
        return True
    if COMPANY_RE.search(text):
        return True
    if AUTHOR_RE.search(text) and re.search(r"(?i)\b(review|meta-regression|study|journal|doi)\b", text):
        return True
    if META_NOISE_RE.search(text):
        return True
    if LECTURE_ADMIN_RE.search(text):
        return True
    if any(x in lower for x in ["generated by", "for external use"]):
        return True
    return False


def main() -> None:
    payload = json.loads(SEED_PATH.read_text(encoding="utf-8"))
    keep = []
    removed = []
    for card in payload.get("cards", []):
        if irrelevant(card):
            removed.append(card)
        else:
            keep.append(card)
    payload["cards"] = keep
    SEED_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"removed {len(removed)} irrelevant cards, kept {len(keep)}")
    for card in removed[:30]:
        print(f"- {card.get('id')}: {plain(card)[:160]}")


if __name__ == "__main__":
    main()
